name: Pull Request Comment Trigger Example
on: [push, pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - name: Check PR Merge
         run: |
             PR_AUTHOR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
             | jq -r .user.login)
             echo "PR Author: $PR_AUTHOR"
