name: Pull Request Comment Trigger Example
on: 
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - name: Fetch Latest PR Number
         id: latest_pr_number
         run: |
             PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
             | jq -r 'map(.number) | max')
             echo "Latest PR Number: $PR_NUMBER"
       - name: Set PR Number as an Output
         id: set_output
         run: echo "PR_NUMBER=${{ steps.latest_pr_number.outputs.PR_NUMBER }}" >> $GITHUB_ENV
          
       - name: Check PR Merge
         id: author
         run: |
             export PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
             | jq -r 'map(.number) | max')
             PR_AUTHOR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
             | jq -r .user.login)
             echo "PR Author: $PR_AUTHOR"
             echo "::set-output name=author::$PR_AUTHOR"
       - name: test
         run: echo ${{ steps.author.outputs.author }}
       - name: send req
         uses: trstringer/manual-approval@v1
         with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.author.outputs.author }}
